### ISSUE TITLE
Crash when editing a level from the pause menu

### ISSUE THREAD

**Issue by Bituvo** [ninXout/Crystal-Client#25] opened 2023-12-03 15:44 UTC
When the "level edit" option is enabled (which allows you to edit any level), my game crashes when I attempt to edit a level.

**Comment by Bituvo** [comment] 2023-12-03 21:18
I run it on Windows, which the mod says it has support for.

**Comment by Bituvo** [comment] 2023-12-04 21:43
I currently don't have access to a recording software.

**Comment by scrahe** [comment] 2023-12-04 21:44
Can you provide a crash log?

**Comment by Bituvo** [comment] 2023-12-09 23:31
```
2023-12-09T18:31:13-0500
Whoopsies! An exception has occurred while running Geode.

== Geode Information ==
Loader Version: v1.3.7
Installed mods: 18
Problems: 0

== Exception Information ==
Faulty Module: GEOMETRYDASHPATH\libcocos2d.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 74010240 (libcocos2d.dll + d0240 (cocos2d::CCGLProgram::use + 0))
Number Parameters: 2

== Stack Trace ==
 - GEOMETRYDASHPATH\libcocos2d.dll + d0240 (cocos2d::CCGLProgram::use + 0)
 - GEOMETRYDASHPATH\libcocos2d.dll + 60cf2 (cocos2d::CCNode::visit + 162)
 - 09AF2E69
 - GEOMETRYDASHPATH\geode\unzipped\geode.devtools\geode.devtools.dll + 649b
 - 09AF2CCB
 - GEOMETRYDASHPATH\GeometryDash.exe + 261175
 - GEOMETRYDASHPATH\GeometryDash.exe + 2621fd
 - C:\Windows\System32\KERNEL32.DLL + 16739 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 68aff (RtlGetFullPathName_UEx + 1215)
 - C:\Windows\SYSTEM32\ntdll.dll + 68acd (RtlGetFullPathName_UEx + 1165)

== Register States ==
EAX: 00000000
EBX: 18890a48
ECX: 00000000
EDX: 00bdf550
EBP: 00bdf624
ESP: 00bdf590
EDI: 155c7f60
ESI: 18890a48
EIP: 74010240

== Installed Mods ==
x | [v1.0.0] capeling.demons_in_garage
x | [v1.3.7] geode.loader
x | [v3.0.11] cvolton.betterinfo
x | [v1.0.4-beta] camila314.betterloading
x | [v2.2.5] alk.small-additions
x | [v1.0.0] camila314.editor-hitbox-fix
x | [v1.1.0] cgytrus.menu-shaders
x | [v1.3.0] cattodev.gatobot
x | [v1.1.0] cvolton.lists
x | [v0.4.2] dankmeme.globed
x | [v1.2.3] geode.custom-keybinds
x | [v1.2.4] geode.devtools
x | [v1.0.0] kolyah35.clipboardfix
x | [v1.0.0] mat.ffmt
x | [v1.0.2] mat.rgb-color-input
x | [v4.0.1] ninxout.crystalclient
x | [v1.0.1] rlt.gd-multiprofile-mod
x | [v1.0.0] techstudent10.hidepause

```

**Comment by Bituvo** [comment] 2023-12-09 23:39
Actually, this issue seems to happen whenever I press the edit button from the pause menu

**Comment by scrahe** [comment] 2023-12-10 01:29
I don’t think this is caused by crystal client, as the faulty mod is unknown.

**Comment by scrahe** [comment] 2023-12-10 01:35
I just tested it on my own computer, and found that this is not caused by crystal client. My suggestion is to submit it to the geode bug tracker.

**Comment by scrahe** [comment] 2023-12-10 16:29
If you turn off BetterLoading, it should work.

**Comment by scrahe** [comment] 2023-12-10 22:01
Please close this issue here, as I have submitted a issue to the BetterLoading bug tracker.

**Closed** 2023-12-12 21:47 UTC
